#!/usr/bin/perl
#===========================================================
#
#   maidoshow ( show mailing lists program )
#
#-----------------------------------------------------------
#
#   Copyright 2009 Takeshi SAKURAI (takeshi.sakurai@hde.co.jp)
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#===========================================================
use strict;
use Fcntl;
use GDBM_File;

my $dbfile = "./maido.gdbm";
my $delim = "\t";

tie my %db, 'GDBM_File', "$dbfile", O_RDONLY, 0444 or die;
foreach my $key (keys %db) {
  my $emails = $db{$key};
  print $key . ": " . join(" ", split(/$delim/, $emails)) . "\n";
}
untie %db;

exit 0;
